# Generated by Django 3.0.6 on 2020-12-24 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='contact',
            new_name='contact1',
        ),
    ]
